//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWebHotel.HotelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReservaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabTipoField;
        
        private int NochesField;
        
        private double PrecioNocheField;
        
        private System.DateTime CheckinField;
        
        private System.DateTime CheckoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReservaId {
            get {
                return this.ReservaIdField;
            }
            set {
                if ((this.ReservaIdField.Equals(value) != true)) {
                    this.ReservaIdField = value;
                    this.RaisePropertyChanged("ReservaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HabTipo {
            get {
                return this.HabTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabTipoField, value) != true)) {
                    this.HabTipoField = value;
                    this.RaisePropertyChanged("HabTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Noches {
            get {
                return this.NochesField;
            }
            set {
                if ((this.NochesField.Equals(value) != true)) {
                    this.NochesField = value;
                    this.RaisePropertyChanged("Noches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double PrecioNoche {
            get {
                return this.PrecioNocheField;
            }
            set {
                if ((this.PrecioNocheField.Equals(value) != true)) {
                    this.PrecioNocheField = value;
                    this.RaisePropertyChanged("PrecioNoche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime Checkin {
            get {
                return this.CheckinField;
            }
            set {
                if ((this.CheckinField.Equals(value) != true)) {
                    this.CheckinField = value;
                    this.RaisePropertyChanged("Checkin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime Checkout {
            get {
                return this.CheckoutField;
            }
            set {
                if ((this.CheckoutField.Equals(value) != true)) {
                    this.CheckoutField = value;
                    this.RaisePropertyChanged("Checkout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.HotelService1Soap")]
    public interface HotelService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerReservaPorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerReservaPorId", ReplyAction="*")]
        ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse ObtenerReservaPorId(ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerReservaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse> ObtenerReservaPorIdAsync(ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerReservaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerReservaPorId", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequestBody Body;
        
        public ObtenerReservaPorIdRequest() {
        }
        
        public ObtenerReservaPorIdRequest(ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerReservaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int reservaId;
        
        public ObtenerReservaPorIdRequestBody() {
        }
        
        public ObtenerReservaPorIdRequestBody(int reservaId) {
            this.reservaId = reservaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerReservaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerReservaPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponseBody Body;
        
        public ObtenerReservaPorIdResponse() {
        }
        
        public ObtenerReservaPorIdResponse(ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerReservaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiciosWebHotel.HotelService.Reserva ObtenerReservaPorIdResult;
        
        public ObtenerReservaPorIdResponseBody() {
        }
        
        public ObtenerReservaPorIdResponseBody(ServiciosWebHotel.HotelService.Reserva ObtenerReservaPorIdResult) {
            this.ObtenerReservaPorIdResult = ObtenerReservaPorIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelService1SoapChannel : ServiciosWebHotel.HotelService.HotelService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelService1SoapClient : System.ServiceModel.ClientBase<ServiciosWebHotel.HotelService.HotelService1Soap>, ServiciosWebHotel.HotelService.HotelService1Soap {
        
        public HotelService1SoapClient() {
        }
        
        public HotelService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse ServiciosWebHotel.HotelService.HotelService1Soap.ObtenerReservaPorId(ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest request) {
            return base.Channel.ObtenerReservaPorId(request);
        }
        
        public ServiciosWebHotel.HotelService.Reserva ObtenerReservaPorId(int reservaId) {
            ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest inValue = new ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest();
            inValue.Body = new ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequestBody();
            inValue.Body.reservaId = reservaId;
            ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse retVal = ((ServiciosWebHotel.HotelService.HotelService1Soap)(this)).ObtenerReservaPorId(inValue);
            return retVal.Body.ObtenerReservaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse> ServiciosWebHotel.HotelService.HotelService1Soap.ObtenerReservaPorIdAsync(ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest request) {
            return base.Channel.ObtenerReservaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWebHotel.HotelService.ObtenerReservaPorIdResponse> ObtenerReservaPorIdAsync(int reservaId) {
            ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest inValue = new ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequest();
            inValue.Body = new ServiciosWebHotel.HotelService.ObtenerReservaPorIdRequestBody();
            inValue.Body.reservaId = reservaId;
            return ((ServiciosWebHotel.HotelService.HotelService1Soap)(this)).ObtenerReservaPorIdAsync(inValue);
        }
    }
}
