//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWebHotel.ReservaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva2", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWebHotel")]
    [System.SerializableAttribute()]
    public partial class Reserva2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NochesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioNocheField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Checkin {
            get {
                return this.CheckinField;
            }
            set {
                if ((this.CheckinField.Equals(value) != true)) {
                    this.CheckinField = value;
                    this.RaisePropertyChanged("Checkin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Checkout {
            get {
                return this.CheckoutField;
            }
            set {
                if ((this.CheckoutField.Equals(value) != true)) {
                    this.CheckoutField = value;
                    this.RaisePropertyChanged("Checkout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HabTipo {
            get {
                return this.HabTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.HabTipoField, value) != true)) {
                    this.HabTipoField = value;
                    this.RaisePropertyChanged("HabTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Noches {
            get {
                return this.NochesField;
            }
            set {
                if ((this.NochesField.Equals(value) != true)) {
                    this.NochesField = value;
                    this.RaisePropertyChanged("Noches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioNoche {
            get {
                return this.PrecioNocheField;
            }
            set {
                if ((this.PrecioNocheField.Equals(value) != true)) {
                    this.PrecioNocheField = value;
                    this.RaisePropertyChanged("PrecioNoche");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservaServiceReference.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/AgregarReserva", ReplyAction="http://tempuri.org/IReservaService/AgregarReservaResponse")]
        bool AgregarReserva(ServiciosWebHotel.ReservaServiceReference.Reserva2 nuevaReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/AgregarReserva", ReplyAction="http://tempuri.org/IReservaService/AgregarReservaResponse")]
        System.Threading.Tasks.Task<bool> AgregarReservaAsync(ServiciosWebHotel.ReservaServiceReference.Reserva2 nuevaReserva);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : ServiciosWebHotel.ReservaServiceReference.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<ServiciosWebHotel.ReservaServiceReference.IReservaService>, ServiciosWebHotel.ReservaServiceReference.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AgregarReserva(ServiciosWebHotel.ReservaServiceReference.Reserva2 nuevaReserva) {
            return base.Channel.AgregarReserva(nuevaReserva);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarReservaAsync(ServiciosWebHotel.ReservaServiceReference.Reserva2 nuevaReserva) {
            return base.Channel.AgregarReservaAsync(nuevaReserva);
        }

        internal bool AgregarReserva(ServiciosWebHotel.Reserva2 nuevaReserva)
        {
            throw new NotImplementedException();
        }
    }
}
